### ISSUE TITLE
Failure to compile on Ubuntu and solution

### ISSUE THREAD

**Issue by sam-the-enby** [jtcriswell/linux256#1]
The kernel will fail to compile on Ubuntu with an error message "code model kernel does not support pic mode". From what I've found, this is an issue caused by Ubuntu's GCC compiling PIE's (position independent executable), which the kernel doesn't support.
To fix this, run `export KCFLAGS="-fno-pie"` before running `make bzImage` and, for me (Ubuntu 17.04, GCC 6.3.0-12ubuntu2), it compiles without the error.

**Comment by jtcriswell** [comment]
Is this a problem on the cycle machines?  We only handle problems occurring on the cycle machines; anything else is out of our purview.

**Comment by sam-the-enby** [comment]
I don't know. I was just saying what happened on my machine and how to fix
it. I wouldn't assume so.

**Comment by jtcriswell** [comment]
We don't support machines other than those at the University (i.e., CSUG), so I'm closing this as "wont fix."
